name: My-Test-Task

on: push

jobs:

  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./angular

    steps:
      - uses: actions/checkout@v3
      # make file with current time inside so we can meassure pipeline exectuion total time
      - name: Start time meassure
        run: echo "$(date +%s)" > ./test.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./angular/test.txt
          
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Setup
        run: npm ci

      - name: run tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        
        #send emails block
      
      - name: Send mail if failure
        uses: dawidd6/action-send-mail@v2
        if: failure()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSW }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} stage in workflow "${{ github.workflow }}" of repo:${{ github.repository }} has ${{ job.status }}. Pipeline has stopped.
          to: ${{ secrets.TO }}
          from: ${{ secrets.EMAIL }}
      - name: Send mail if succeess
        uses: dawidd6/action-send-mail@v2
        if: success()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSW }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} stage in workflow "${{ github.workflow }}" of repo:${{ github.repository }} has ${{ job.status }}
          to: ${{ secrets.TO }}
          from: ${{ secrets.EMAIL }}
        
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./angular
    permissions:
      contents: read
      packages: write
    needs: tests
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: setup
        run: npm ci

      - name: build
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ghcr.io/${{ github.repository }}/v.${{ github.run_number }}
    
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ./angular

      # here we store our total time into Enviroment variable, so we can pass it in email later.
      - name: count total time
        run: |
          start_time=$(cat ./test.txt)
          #added 20 sec to cover time while pipeline started
          echo "TOTAL_TIME=$(( $(date +%s) - start_time + 20 ))" >> $GITHUB_ENV
          
        #send emails block
      - name: Send mail if failure
        uses: dawidd6/action-send-mail@v2
        if: failure()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSW }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} stage in workflow "${{ github.workflow }}" of repo:${{ github.repository }} has ${{ job.status }}. Pipeline has stopped.
          to: ${{ secrets.TO }}
          from: ${{ secrets.EMAIL }}
      - name: Send mail if succeess
        uses: dawidd6/action-send-mail@v2
        if: success()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSW }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} stage in workflow "${{ github.workflow }}" of repo:${{ github.repository }} has ${{ job.status }}
          to: ${{ secrets.TO }}
          from: ${{ secrets.EMAIL }}
      - name: Send total time via email
        uses: dawidd6/action-send-mail@v2
        if: success()
        with:
         server_address: smtp.gmail.com
         server_port: 465
         username: ${{ secrets.EMAIL }}
         password: ${{ secrets.PASSW }}
         subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
         body: Entire pipeline in workflow "${{ github.workflow }}" of repo:${{ github.repository }} has took aproximattely ${{ env.TOTAL_TIME }} seconds to execute
         to: ${{ secrets.TO }}
         from: ${{ secrets.EMAIL }}
