name: My-Test-Task

on: push

jobs:

  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./angular

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Setup
        run: npm ci

      - name: run tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./angular
    permissions:
      contents: read
      packages: write
    needs: tests
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup
        run: npm ci

      - name: build
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/v.${{ github.run_number }}
